# spring.application.name=nguyenquoctrung
# Database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/cakestore?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password=
# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.jakarta.persistence.validation.mode=none

# Spring Security
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# Đọc file .env nếu có (Spring Boot 2.4+ hỗ trợ cấu trúc này)
spring.config.import=optional:file:.env[.properties], optional:file:../.env[.properties], optional:file:./doanmon/.env[.properties]

#Nhập thông tin Client Id và Client Secret từ Google Cloud Console
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}

server.error.path=/error